<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Convertisseur de Devises</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>Convertisseur de Devises</h1>
        <div class="converter">
            <label for="amount">Montant :</label>
            <input type="number" id="amount" placeholder="Entrez un montant" />
            
            <label for="from-currency">De :</label>
            <select id="from-currency">
                <option value="EUR">EUR - Euro</option>
                <option value="USD">USD - Dollar</option>
                <option value="GBP">GBP - Livre</option>
            </select>

            <label for="to-currency">À :</label>
            <select id="to-currency">
                <option value="USD">USD - Dollar</option>
                <option value="EUR">EUR - Euro</option>
                <option value="GBP">GBP - Livre</option>
            </select>

            <button id="convert-btn">Convertir</button>

            <h2 id="result">Résultat : -</h2>
        </div>
    </div>
    <script src="script.js"></script>
</body>
</html>

body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f9;
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.container {
    background: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    text-align: center;
    width: 300px;
}

h1 {
    margin-bottom: 20px;
    color: #333;
}

label {
    display: block;
    margin: 10px 0 5px;
    font-weight: bold;
}

input, select {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ddd;
    border-radius: 5px;
}

button {
    padding: 10px 15px;
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

button:hover {
    background-color: #0056b3;
}

h2 {
    margin-top: 20px;
    color: #333;
}

// Fonction de conversion
document.getElementById("convert-btn").addEventListener("click", () => {
    const amount = parseFloat(document.getElementById("amount").value);
    const fromCurrency = document.getElementById("from-currency").value;
    const toCurrency = document.getElementById("to-currency").value;

    if (isNaN(amount) || amount <= 0) {
        alert("Veuillez entrer un montant valide !");
        return;
    }

    // Taux de conversion fictifs
    const exchangeRates = {
        EUR: { USD: 1.1, GBP: 0.85 },
        USD: { EUR: 0.91, GBP: 0.77 },
        GBP: { EUR: 1.18, USD: 1.3 }
    };

    if (fromCurrency === toCurrency) {
        document.getElementById("result").textContent = `Résultat : ${amount.toFixed(2)} ${toCurrency}`;
        return;
    }

    const rate = exchangeRates[fromCurrency][toCurrency];
    const convertedAmount = (amount * rate).toFixed(2);

    document.getElementById("result").textContent = `Résultat : ${convertedAmount} ${toCurrency}`;
});